// Exportamos una funci贸n que toma otra funci贸n 'func' como argumento.
module.exports = func => {
    // Retornamos una nueva funci贸n que toma los argumentos 'req', 'res', y 'next'.
    return (req, res, next) => {
        // Ejecutamos la funci贸n 'func' pasando 'req', 'res', y 'next', y manejamos cualquier error que ocurra usando 'catch(next)'.
        func(req, res, next).catch(next);
    };
};
